version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "America/Sao_Paulo"
    groups:
      python-packages:
        patterns:
          - "*"
    assignees:
      - "cardoso-neto"
    reviewers:
      - "jwehrmann"
    target-branch: "master"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
      ignore:
      - dependency-name: "pydantic"
        versions: ["2.x"]
    rebase-strategy: "auto"
